sudo: required

language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # ARTIFACTORY_USERNAME
  - secure: "NgenwflUM56xJU/uYXzRCLoq+atktBUpF9P0oAu2q+5UWCNP9wGXEu1hO3BxQBSza9Q11q6XwbZ7r8ovn1Ac5Olv+ejFxJz5Jxqd6an49CBAmM03ER4klVUkaX1B5epFefrYz9OISqupt77TIL6pYFZ6sXe1bQSFdscnl9O8QyR3Lwjoc+RyUDCZ8I1V8VNuXL9/vpHK2kHijk1Tky3aIGwt2wGYXfKN0wsDajYAhiZ9++MCDLRazrSIeNIyw3QMBoAMekmbCm3Ooat85V1tKoEovVJ6+tIbyCIU+rxSzRvMBOhUrjhHPahTtEBG94/u1pMDwBVBw1M4IfIjwSm7++ELwr4GZabfaCQusR/fXQBFYe32uZC+G0zHremkxHw2XKRwvei2eFfHQBcByKvRIF3wcHpD766ysCgN0IAVEKeZtah0jK/1REixyI3VPZz4g1BfyNGrMIoHQcyp/di9bTL3Kd7AJfL1yN++xxM9dqsqngVWAVclHoaFxzUkf+v8A1uAa41c+GJJvozlyP1JQB69sYHUGTVd7yDVYh7jN9h5ASm0BOcEhiOuWeAlOgXc2j8a7Mv8drGY1O+IHIbvCMxar4B3ZoBcxck/KxFKAUxMZFCzykieSMIKjEVnUD48IWT44cj4nwiTMd82PHkg/LL9TG6togsyZuhvXWP4sAM="
  # ARTIFACTORY_PASSWORD
  - secure: "0aN29zTPkg8yYyEosC4e0X9IMh/bhXFxN2CCm5PjUID7jqL3nyaUwTHuImVZgttOSQOTrIZRd/52H8NGU1jl5f0vJxH+ZEjfMSR0w+9+z2KORE/7W51XWfmtW6c/3UZ2TuexpZUZNkqMkvE9WWKBr3sV3/nZG3D3Mq3J/cEUCURZshU2VcUas1A8wznXzFsYRZ0SHQFWD5lv52wlf1bCEnW2T2GVat2CgwSS9OTuBlE3yuPktao7MtZolFnb4+0HbHkjCPXf0ilZeMuQiqY71Wse+p4qhIGw26McMs8TWw6ZUz9x+tEC5diqTty84MNud8WBSDBQ72tkxnQB8/DRrjdASxoHhwDBVvXk36rUpc+KhC0WTZ2X4RaATRAuBHK+e5WqSO33Sg72bJn0cUNgM2U+B0wcyx5u4/UKXXGcV5mR5J72dl0z4dLvjE3AivLn7Ep2cBNZRBuON7Lb82aPiTWQ0fik1jkTGBBlBxR+7TMvoJShSv/a3ouFExhR3i/yz50S0254Qlrcbg7sYyUb23za1zaSJZ1gDhlLS6gmYtjIK+t03FBEy9Ydy+oupDGQu9uaADuk4tTJvauKZaaYEzjdaAYEKA2svJawS5GRB52KEASQ+ARqlDgQpJIPjMQT8DX8W5uFr1QQOBe/HaYagkINBfMD38pq14yyjF30fh4="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export TZ=Europe/Helsinki

script:
- mvn clean package

deploy:
  provider: script
  script: "mvn deploy -DskipTests --settings ci-tools/common/maven-settings.xml"
  skip_cleanup: true
  on:
    branch: OY-110__escape_changes