package fi.vm.sade.auditlog.oppijanumerorekisteri;

public enum OppijanumerorekisteriOperation {
    CREATE_HENKILO,
    UPDATE_HENKILO,
    PASSIVOI_HENKILO,
    TUNNISTUSTIETOJEN_PAIVITYS,
    YKSILOINTITIETOJEN_PAIVITYS,
    MANUAALINEN_YKSILOINTI,
    YKSILOINTI_PAALLE,
    YKSILOINTI_POIS_PAALTA,
    HETUTTOMAN_YKSILOINTI,
    PURA_HETUTTOMAN_YKSILOINTI
}
